zmodload zsh/zprof



{
    # Execute code in the background to not affect the current session
    export ZSH_COMPDUMP="$ZSH_CACHE_DIR/zcompdump-$HOST"
    autoload -Uz compinit
    if [ ! -f $ZSH_COMPDUMP ]; then
        compinit -d $ZSH_COMPDUMP
        zcompile "$ZSH_COMPDUMP"
    else

        if [ $(date +'%j') != $(/usr/bin/stat -f '%Sm' -t '%j' ${ZSH_COMPDUMP} ) ]; then
            compinit -d ${ZSH_COMPDUMP}
        else
            compinit -C
        fi

  # Compile zcompdump, if modified, to increase startup speed.
        if [[ -s "$ZSH_COMPDUMP" && (! -s "${zcompdump}.zwc" || "$ZSH_COMPDUMP" -nt "${ZSH_COMPDUMP}.zwc") ]]; then
            zcompile "$ZSH_COMPDUMP"
        fi
    fi
} &!
